version: '3'

services:
  app:
    build: .
    container_name: fund-app
    depends_on:
      - fund-db
    links:
      - fund-db
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=backend/flaskapp.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres@fund-db:5432/fund_dev
      - DATABASE_PROD_URL=postgres://postgres@fund-db:5432/fund_prod
      - DATABASE_TEST_URL=postgres://postgres@fund-db:5432/fund_test
  fund-db:
    image: postgres:latest
    container_name: fund-db
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    expose:
      - "5432"
    environment:
    - POSTGRES_USER=postgres
